name: RedProtect
main: br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect
version: ${project.version}
api-version: "1.13"
author: FabioZumbi12
description: Allows players to define fields to protect their houses.
softdepend: [WorldEdit, BossbarAPI, MyChunk, MyPet, Multiverse-Core, mcMMO, SkillAPI, MagicCarpet, PvPManager, Essentials, dynmap, SimpleClans, Factions, PlaceholderAPI, GriefPrevention]
commands:
  RedProtect:
    description: "Main command for RedProtect."
    usage: "Error, use '/rp ?' to see the commands."
    aliases: [rp]
permissions:
  redprotect.*:
    description: "All redprotect commands."
    default: op
    children:
      redprotect.command.user: true
      redprotect.command.admin: true
  redprotect.command.user:
    description: "Recommended User permissions."
    default: true
    children:
      redprotect.command.help: true
      redprotect.command.border: true
      redprotect.command.ldeny: true
      redprotect.command.laccept: true
      redprotect.command.claim: true
      redprotect.command.expand-vert: true
      redprotect.command.delete: true
      redprotect.command.info: true
      redprotect.command.addmember: true
      redprotect.command.addleader: true
      redprotect.command.addadmin: true
      redprotect.command.removemember: true
      redprotect.command.removeadmin: true
      redprotect.command.removeleader: true
      redprotect.command.rename: true
      redprotect.command.welcome: true
      redprotect.command.blocklimit: true
      redprotect.command.claimlimit: true
      redprotect.command.list: true
      redprotect.command.priority: true
      redprotect.command.flag: true
      redprotect.command.near: true
      redprotect.command.kick: true
      redprotect.command.teleport: true
      redprotect.command.settp: true
      redprotect.command.deltp: true
      redprotect.command.infowand: true
      redprotect.command.wand: true
  redprotect.command.admin:
    description: "Recommended Admin permsisions."
    default: op
    children:
      redprotect.command.admin.claim: true
      redprotect.command.admin.wand: true
      redprotect.command.admin.create: true
      redprotect.command.admin.delete: true
      redprotect.command.admin.removeadmin: true
      redprotect.command.admin.addadmin: true
      redprotect.command.admin.removeleader: true
      redprotect.command.admin.addleader: true
      redprotect.command.admin.addmember: true
      redprotect.command.admin.removemember: true
      redprotect.command.admin.info: true
      redprotect.command.admin.priority: true
      redprotect.command.admin.rename: true
      redprotect.command.admin.welcome: true
      redprotect.command.admin.define: true
      redprotect.command.admin.createportal: true
      redprotect.command.admin.reload: true
      redprotect.command.admin.save-all: true
      redprotect.command.admin.load-all: true
      redprotect.command.admin.teleport: true
      redprotect.command.admin.copyflag: true
      redprotect.command.admin.setconfig: true
      redprotect.command.admin.settp: true
      redprotect.command.admin.deltp: true
      redprotect.command.admin.value: true
      redprotect.command.admin.expandvert: true
      redprotect.command.admin.setmaxy: true
      redprotect.command.admin.setminy: true
      redprotect.command.admin.border: true
      redprotect.command.admin.redefine: true
      redprotect.command.admin.gui-edit: true
      redprotect.command.teleport.other: true
      redprotect.command.admin.blocklimit: true
      redprotect.command.admin.claimlimit: true
      redprotect.command.removeall: true
      redprotect.command.regenall: true
      redprotect.command.start: true
      redprotect.command.list-areas: true
      redprotect.command.select-we: true
      redprotect.command.addleader.bypass: true
      redprotect.command.regen: true
      redprotect.limits.claim.unlimited: true
      redprotect.limits.blocks.unlimited: true
      redprotect.command-range-bypass: true
      redprotect.bypass: true
      redprotect.bypass.world: true
      redprotect.bypass.nether-roof: true
      redprotect.bypass.velocity: true
      redprotect.bypass.define-max-distance: true
      redprotect.signspy: true
      redprotect.eco.use: true
      redprotect.eco.admin: true
      redprotect.eco.setvalue: true
      redprotect.eco.others: true
      redprotect.eco.bypass: true
      redprotect.use-claim-modes: true